jsdata = {'186.121.249.109': {'osmatch': {}, 'ports': [{'protocol': 'tcp', 'portid': '80', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'http', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '135', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'msrpc', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '139', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'netbios-ssn', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '1028', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'unknown', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '1033', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'netinfo', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '2103', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'zephyr-clt', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '2105', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'eklogin', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '2107', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'msmq-mgmt', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '3389', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'ms-wbt-server', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}, {'protocol': 'tcp', 'portid': '5357', 'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '0', 'service': {'name': 'wsdapi', 'method': 'table', 'conf': '3'}, 'cpe': [], 'scripts': []}], 'hostname': [{'name': 'static-186-121-249-109.acelerate.net', 'type': 'PTR'}], 'macaddress': None, 'state': {'state': 'up', 'reason': 'echo-reply', 'reason_ttl': '111'}}, 'runtime': {'time': '1669853079', 'timestr': 'Wed Nov 30 20:04:39 2022', 'summary': 'Nmap done at Wed Nov 30 20:04:39 2022; 1 IP address (1 host up) scanned in 44.52 seconds', 'elapsed': '44.52', 'exit': 'success'}, 'stats': {'scanner': 'nmap', 'args': '"C:/Program Files (x86)/Nmap/nmap.exe" -v -oX - -sT 186.121.249.109', 'start': '1669853035', 'startstr': 'Wed Nov 30 20:03:55 2022', 'version': '7.93', 'xmloutputversion': '1.05'}, 'task_results': [{'task': 'Ping Scan', 'time': '1669853035', 'extrainfo': '1 total hosts'}, {'task': 'Parallel DNS resolution of 1 host.', 'time': '1669853035'}, {'task': 'Connect Scan', 'time': '1669853079', 'extrainfo': '1000 total ports'}]}
ports = jsdata['186.121.249.109']["ports"]


def scan():
    open_port = ""
    for port in ports:
        #print(port["service"]["name"])
        open_port += (port.get("portid") + " : " + port["service"]["name"]) + "\n"
        
    return open_port

print(scan())